#!/bin/bash
set -e

ssh "$SSH_USER@$SSH_HOST" "cat > $DOCKER_COMPOSE_PATH/.env <<EOL
NEXT_PUBLIC_APP_NAME=$FRONTEND_APP_NAME
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
EOL
"